openapi:  3.0.1

info:
  title: Data4Life Password-Checker
  description: Proxy to haveibeenpwned.com
  x-audience: external
  version: 1.0.0

servers:
  - url: https://api-phdp-sandbox.hpsgc.de
    description: Sandbox environment
  - url: https://api.data4life.care
    description: Production environment
  
paths:
  /password/range/{hash_prefix}:
    get:
      summary: Return a list of matching password hashes.
      description: Expects the first 5 characters of the sha1sum of the password. A text/plain list of the last 35 characters is send to verify if the password is leaked or not. After the first 35 characters there is a colon followed by the number of times th:we password is found in different databases.
      responses:
        200: 
          description: A list of postfix hashes that should be checked by the client to verify that the used password didn't leak.
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/HashList'
        400:
          description: Is returned when the hash_prefix isn't exactly 5 hexadecimal characters long.
        429:
          description: Isn't documented on HIBP, but is logged as an internal server error to cause awareness on the alerting side.
        500:
          description: Is returned when the service isn't able to connect to HIBP or the copying of the response to the user fails.

components:
  schemas:
    HashList:
      type: array
      items:
        $ref: '#/components/schemas/HashCount'
    HashCount:
      type: string
      format: '{hash postfix}:{count}'
